version: '3.7'

services:
  psql-13:
    image: postgres:13
    user: postgres:postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-md5}"
      POSTGRES_USER: test_username
      POSTGRES_DB: test_database
      POSTGRES_PASSWORD: test_password
    ports:
      - 5432:5432
  psql-12:
    image: postgres:12
    user: postgres:postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-md5}"
      POSTGRES_USER: test_username
      POSTGRES_DB: test_database
      POSTGRES_PASSWORD: test_password
    ports:
      - 5432:5432
  psql-11:
    image: postgres:11
    user: postgres:postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-md5}"
      POSTGRES_USER: test_username
      POSTGRES_DB: test_database
      POSTGRES_PASSWORD: test_password
    ports:
      - 5432:5432
