name: CI for main
on:
  push:
    branches:
      - main
jobs:
  update-main-codecov:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@reusable-workflows
    with:
      with_coverage: true
      with_tsan: true
      coverage_ignores: '/Tests/'
      test_filter: '^PostgresNIOTests'
