name: issue-to-project-board-workflow
on:
  # Trigger when an issue gets labeled or deleted
  issues:
    types: [reopened, closed, labeled, unlabeled, assigned, unassigned]

jobs:
  manage_project_issues:
    uses: vapor/ci/.github/workflows/issues-to-project-board.yml@reusable-workflows
    with:
      labelsJson: ${{ toJSON(github.event.issue.labels.*.name || []) }}
    secrets: inherit
