name: test
on:
- pull_request
jobs:
  postgres-nio:
    container: 
      image: vapor/swift:5.2
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  postgres-kit:
    container: 
      image: vapor/swift:5.2
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    steps:
    - run: git clone -b master https://github.com/vapor/postgres-kit.git
      working-directory: ./
    - run: swift package edit postgres-nio --revision ${{ github.sha }}
      working-directory: ./postgres-kit
    - run: swift test --enable-test-discovery --sanitize=thread
      working-directory: ./postgres-kit
      env:
        POSTGRES_HOSTNAME: psql
  fluent-postgres-driver:
    container: 
      image: vapor/swift:5.2
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    steps:
    - run: git clone -b master https://github.com/vapor/fluent-postgres-driver.git
      working-directory: ./
    - run: swift package edit postgres-nio --revision ${{ github.sha }}
      working-directory: ./fluent-postgres-driver
    - run: swift test --enable-test-discovery --sanitize=thread
      working-directory: ./fluent-postgres-driver
      env:
        POSTGRES_HOSTNAME: psql
