name: test
on: [ 'pull_request' ]
env:
  LOG_LEVEL: notice

jobs:
  linux-unit:
    strategy:
      fail-fast: false
      matrix:
        swiftver:
          - swift:5.2
          - swift:5.5
          - swiftlang/swift:nightly-main
        swiftos:
          - focal
    container: ${{ format('{0}-{1}', matrix.swiftver, matrix.swiftos) }}
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: debug
      MATRIX_CONFIG: ${{ toJSON(matrix) }}
    steps:
      - name: Check out package
        uses: actions/checkout@v2
      - name: Run unit tests with code coverage
        run: swift test --enable-test-discovery --filter=^PostgresNIOTests --enable-code-coverage
      - name: Convert code coverage report to most expressive format
        run: |
          export pkgname="$(swift package dump-package | perl -e 'use JSON::PP; print (decode_json(join("",(<>)))->{name});')" \
                 subpath="$([ "$(uname -s)" = 'Darwin' ] && echo "/Contents/MacOS/${pkgname}PackageTests" || true)" \
                 exc_prefix="$(which xcrun || true)" && \
          ${exc_prefix} llvm-cov export -format lcov \
              -instr-profile="$(dirname "$(swift test --show-codecov-path)")/default.profdata" \
              --ignore-filename-regex='\.build/' \
              "$(swift build --show-bin-path)/${pkgname}PackageTests.xctest${subpath}" \
              >"${pkgname}.lcov"
          echo "CODECOV_FILE=$(pwd)/${pkgname}.lcov" >> $GITHUB_ENV
      - name: Send coverage report to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ${{ env.CODECOV_FILE }}
          flags: 'unittests'
          env_vars: 'MATRIX_CONFIG'
          fail_ci_if_error: true

  linux-integration-and-dependencies:
    strategy:
      fail-fast: false
      matrix:
        dbimage:
          - postgres:14
          - postgres:13
          - postgres:12
          - postgres:11
        dbauth:
          - trust
          - md5
          - scram-sha-256
        swiftver:
          - swift:5.2
          - swift:5.5
          - swiftlang/swift:nightly-main
        swiftos:
          - focal
    container: ${{ format('{0}-{1}', matrix.swiftver, matrix.swiftos) }}
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: debug
      # Unfortunately, fluent-postgres-driver details leak through here
      POSTGRES_HOSTNAME: 'psql-a'
      POSTGRES_DB: 'test_database'
      POSTGRES_DATABASE: 'test_database'
      POSTGRES_DATABASE_A: 'test_database'
      POSTGRES_DATABASE_B: 'test_database'
      POSTGRES_USER: 'test_username'
      POSTGRES_USERNAME: 'test_username'
      POSTGRES_USERNAME_A: 'test_username'
      POSTGRES_USERNAME_B: 'test_username'
      POSTGRES_PASSWORD: 'test_password'
      POSTGRES_PASSWORD_A: 'test_password'
      POSTGRES_PASSWORD_B: 'test_password'
      POSTGRES_HOSTNAME_A: 'psql-a'
      POSTGRES_HOSTNAME_B: 'psql-b'
      POSTGRES_HOST_AUTH_METHOD: ${{ matrix.dbauth }}
    services:
      psql-a:
        image: ${{ matrix.dbimage }}
        env:
          POSTGRES_USER: 'test_username'
          POSTGRES_DB: 'test_database'
          POSTGRES_PASSWORD: 'test_password'
          POSTGRES_HOST_AUTH_METHOD: ${{ matrix.dbauth }}
          POSTGRES_INITDB_ARGS: --auth-host=${{ matrix.dbauth }}
      psql-b:
        image: ${{ matrix.dbimage }}
        env:
          POSTGRES_USER: 'test_username'
          POSTGRES_DB: 'test_database'
          POSTGRES_PASSWORD: 'test_password'
          POSTGRES_HOST_AUTH_METHOD: ${{ matrix.dbauth }}
          POSTGRES_INITDB_ARGS: --auth-host=${{ matrix.dbauth }}
    steps:
      - name: Check out package
        uses: actions/checkout@v2
        with: { path: 'postgres-nio' }
      - name: Run integration tests
        run: swift test --package-path postgres-nio --enable-test-discovery --filter=^IntegrationTests
      - name: Check out postgres-kit dependent
        uses: actions/checkout@v2
        with: { repository: 'vapor/postgres-kit', path: 'postgres-kit' }
      - name: Check out fluent-postgres-driver dependent
        uses: actions/checkout@v2
        with: { repository: 'vapor/fluent-postgres-driver', path: 'fluent-postgres-driver' }
      - name: Use local package in dependents
        run: |
          swift package --package-path postgres-kit edit postgres-nio --path postgres-nio
          swift package --package-path fluent-postgres-driver edit postgres-nio --path postgres-nio
      - name: Run postgres-kit tests
        run: swift test --package-path postgres-kit --enable-test-discovery
      - name: Run fluent-postgres-driver tests
        run: swift test --package-path fluent-postgres-driver --enable-test-discovery

  macos-all:
    strategy:
      fail-fast: false
      matrix:
        dbimage:
          # Only test the lastest couple of versions on macOS, let Linux do the rest
          - postgresql@14
          - postgresql@13
          # - postgresql@12
          # - postgresql@11
        dbauth:
          # Only test one auth method on macOS, Linux tests will cover the others
          # - trust
          # - md5
          - scram-sha-256
        xcode:
          - latest-stable
          - latest
    runs-on: macos-11
    env:
      LOG_LEVEL: debug
      POSTGRES_HOSTNAME: 127.0.0.1
      POSTGRES_USER: 'test_username'
      POSTGRES_PASSWORD: 'test_password'
      POSTGRES_DB: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: ${{ matrix.dbauth }}
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Install Postgres, setup DB and auth, and wait for server start
        run: |
          export PATH="$(brew prefix)/opt/${{ matrix.dbimage }}/bin:$PATH" PGDATA=/tmp/vapor-postgres-test
          brew install ${{ matrix.dbimage }}
          initdb --locale=C --auth-host ${{ matrix.dbauth }} -U $POSTGRES_USER --pwfile=<(echo $POSTGRES_PASSWORD)
          pg_ctl start --wait
        timeout-minutes: 2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run all tests
        run: |
          swift test --enable-test-discovery -Xlinker -rpath \
                -Xlinker $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx
